name: ikiadim
description: A Flutter Two Factor Authenticator App
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_dotenv: ^5.0.2
    flutter_jailbreak_detection: ^1.8.0
    flutter_secure_storage: ^4.2.1
    google_fonts: ^2.1.0
    hive: ^2.0.4
    hive_flutter: ^1.1.0
    otp: ^3.0.1
    qr_code_scanner: ^0.5.2
    sentry_flutter: ^6.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0
    hive_generator: ^1.1.1
    build_runner: ^2.1.4
    flutter_launcher_icons: ^0.9.2
    test: ^1.17.10
    flutter_native_splash: ^1.3.1

flutter_icons:
    image_path: "assets/images/AppIcon.png"
    android: true
    ios: true
    adaptive_icon_background: "#194073"
    adaptive_icon_foreground: "assets/images/foreground.png"

flutter_native_splash:
    # flutter pub run flutter_native_splash:create
    # flutter pub run flutter_native_splash:remove

    color: "#194073"
    #background_image: "assets/background.png"
    image: assets/images/slice.png
    #color_dark: "#042a49"
    #background_image_dark: "assets/dark-background.png"
    #image_dark: assets/splash-invert.png

    #android: false
    #ios: false
    #web: false

    #android_gravity: center
    #ios_content_mode: center
    #web_image_mode: center

flutter:
    uses-material-design: true
    assets:
        - .env
